# Generated by Django 2.2.7 on 2019-11-12 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baatkare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatmsg', models.TextField()),
                ('msgdate', models.DateField()),
                ('oppsbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foroppsbot', to=settings.AUTH_USER_MODEL)),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foruserbot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
