# Generated by Django 2.2.7 on 2019-11-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_auto_20191112_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baatkare',
            name='reply',
            field=models.IntegerField(),
        ),
    ]
